channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=23.1.2
- pip:
  - mlflow<3,>=2.3
  - cloudpickle==2.0.0
  - lz4==3.1.3
  - numpy==1.21.5
  - psutil==5.9.2
  - scikit-learn==1.2.2
  - scipy==1.9.3
  - typing-extensions==4.7.0
name: mlflow-env
