stages:
  data_ingestion:
    cmd: python3 src/pipeline/stage_01_data_ingestion.py
    deps:
    - src/pipeline/stage_01_data_ingestion.py
    outs:
    - data/raw/stroke-data.zip
    - data/raw/healthcare-dataset-stroke-data.csv

  data_preprocessing:
    cmd: python3 src/pipeline/stage_02_data_preprocessing.py
    deps:
    - src/pipeline/stage_02_data_preprocessing.py
    outs:
    - data/processed/train_stroke.csv
    - data/processed/test_stroke.csv