name: Build and Push Docker Image

on:
  push:
    # branches: [ main ]
    branches: [ trybranch ]


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t fraidoonjan/stroke_predictor:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push fraidoonjan/stroke_predictor:${{ github.sha }}
